apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oycmk22za-python
  janus-idp.io/tekton: oycmk22za-python
  backstage.io/kubernetes-id: oycmk22za-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oycmk22za-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
