apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oycmk22za-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oycmk22za-python 
  name: oycmk22za-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oycmk22za-python 
